spring:
  application:
    name: calendar-service
  profiles:
    active: default
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalt-zone: http://localhost:8761/eureka/
server:
  port: 6666
